<a href="https://colab.research.google.com/github/HarlMelendez/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [41]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

A = np.dot(A, B)
B = np.add(D, D)
C = 2 * C
D = ("?")

print("A.) AB = \n", A)
print(end= '')

print("\nB.) D+D = \n", B)
print(end= '')

print("\nC.) 2C = \n", C)
print(end=" ")

print("\nD.) N/A =", D)

A.) AB = 
 [[22 28]
 [49 64]]

B.) D+D = 
 [[2 4]
 [6 8]]

C.) 2C = 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
 
D.) N/A = ?


Problem 2

In [42]:
import numpy as np

A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

Solution = [(A[1]*B[2])-(A[2]*B[1]), (A[2]*B[0])-(A[0]*B[2]),(A[0]*B[1])-(A[1]*B[0])]

print("Final Answer:", Solution)

Final Answer: [20, -4, -3]
