<a href="https://colab.research.google.com/github/HarlMelendez/58013-Linear-Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

In [ ]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

Associative

In [12]:
import numpy as np

A = np.array([[1, 2, 3],
              [9, 8, 7],
              [5, 6, 4]])

B = np.array([[9, 8, 7],
              [5, 6, 4],
              [1, 2, 3]])

C = np.array([[5, 6, 4],
              [1, 2, 3],
              [9, 8, 7]])

Asso1 = np.dot(np.dot(A, B), C)

Asso2 = np.dot(A, np.dot(B, C))

print("(A * B) * C =")
print(Asso1)
print("A * (B * C) =")
print(Asso2)

are_equal = np.array_equal(Asso1, Asso2)
print("\nAre the two sides equal? {}".format(are_equal))

(A * B) * C =
[[ 352  376  334]
 [1818 1964 1726]
 [1118 1210 1065]]
A * (B * C) =
[[ 352  376  334]
 [1818 1964 1726]
 [1118 1210 1065]]

Are the two sides equal? True


Distributive

In [11]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[5, 4, 6],
              [2, 3, 1],
              [7, 8, 9]])
dis1 = np.dot(A, B + C)
dis2 = np.dot(A, B) + np.dot(A, C)

print("\n(A * (B + C)):")
print(dis1)
print("\n(A * B) + (A * C):")
print(dis2)

are_equal_distributive = np.array_equal(dis1, dis2)
print("\nAre the two sides equal? {}".format(are_equal_distributive))



(A * (B + C)):
[[ 60  58  53]
 [156 148 137]
 [252 238 221]]

(A * B) + (A * C):
[[ 60  58  53]
 [156 148 137]
 [252 238 221]]

Are the two sides equal? True


Identity

In [9]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[5, 4, 6],
              [2, 3, 1],
              [7, 8, 9]])

I = np.eye(3)

result1 = np.dot(A, I)
result2 = np.dot(I, A)

print("\nA * I:")
print(result1)
print("\nI * A:")
print(result2)

are_equal_identity = np.array_equal(result1, A) and np.array_equal(result2, A)
print("\nAre the results equal to A? {}".format(are_equal_identity))


A * I:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

I * A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Are the results equal to A? True


Zero


A * 0:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Is the result equal to the zero matrix? True


Scalar

In [25]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

k = 2

result_scalar_property = k * A

print("\nk * A:")
print(result_scalar_property)



k * A:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Closure

In [29]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

AB = np.dot(A, B)

print("\nMatrix AB (A * B):\n", AB)


Matrix AB (A * B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
