<a href="https://colab.research.google.com/github/HarlMelendez/58013-Linear-Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

X = np.array([[1,1,1],[3,-2,-1],[-1,4,2]], dtype=float)
Y = np.array([[1],[4],[-3]],dtype=float)

print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [21]:
import numpy as np

month1 = np.array([30, 10, 120, 12500], dtype=float)
month2 = np.array([40, 20, 200, 18000], dtype=float)
month3 = np.array([50, 40, 360, 25700], dtype=float)

prices = np.linalg.solve([month1[:-1], month2[:-1], month3[:-1]], [month1[-1], month2[-1], month3[-1]])

flour_price, yeast_price, egg_price = prices
print("Price of flour per sack:", int(flour_price), "pesos")
print("Price of yeast per pack:", int(yeast_price), "pesos")
print("Price of one egg:", int(egg_price), "pesos")

Price of flour per sack: 330 pesos
Price of yeast per pack: 139 pesos
Price of one egg: 10 pesos
