<a href="https://colab.research.google.com/github/HarlMelendez/58013-Linear-Algebra/blob/main/undone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

-235.0000000000002

In [3]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

Associative Multiplication Property

In [7]:
import numpy as np

A = np.array([[1, 2, 3],
              [9, 8, 7],
              [5, 6, 4]])

B = np.array([[9, 8, 7],
              [5, 6, 4],
              [1, 2, 3]])

C = np.array([[5, 6, 4],
              [1, 2, 3],
              [9, 8, 7]])

Asso1 = np.dot(np.dot(A, B), C)

Asso2 = np.dot(A, np.dot(B, C))

if np.array_equal(left_associative, right_associative):
    print("Associative property holds for matrix multiplication.")
    print("(A * B) * C =")
    print(Asso1)
    print("A * (B * C) =")
    print(Asso2)

Associative property holds for matrix multiplication.
(A * B) * C =
[[ 352  376  334]
 [1818 1964 1726]
 [1118 1210 1065]]
A * (B * C) =
[[ 352  376  334]
 [1818 1964 1726]
 [1118 1210 1065]]
